@echo off
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing requirements...
pip install django django-crispy-forms django-bootstrap4 Pillow
echo Creating Django project...
django-admin startproject shoe_shop .
python manage.py startapp shoes
echo Project setup complete!
echo You can now run the development server with:
echo python manage.py runserver
echo Press any key to exit...
